# Generated by Django 5.2.14 on 2026-05-24 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='科目コード')),
                ('name', models.CharField(max_length=50, verbose_name='科目名')),
                ('account_type', models.CharField(choices=[('asset', '資産'), ('revenue', '収益')], max_length=10, verbose_name='科目区分')),
            ],
            options={
                'verbose_name': '勘定科目',
                'verbose_name_plural': '勘定科目',
                'ordering': ['code'],
            },
        ),
    ]
