# Generated by Django 5.2.14 on 2026-05-24 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='仕訳日付')),
                ('side', models.CharField(choices=[('debit', '借方'), ('credit', '貸方')], max_length=6, verbose_name='借貸区分')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='金額')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='摘要')),
                ('group_id', models.IntegerField(blank=True, null=True, verbose_name='仕訳グループID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.account', verbose_name='勘定科目')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journal_entries', to='accounting.customer', verbose_name='得意先')),
            ],
            options={
                'verbose_name': '仕訳',
                'verbose_name_plural': '仕訳',
                'ordering': ['date', 'group_id', 'side'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('sale', '売上'), ('receipt', '入金')], max_length=10, verbose_name='取引種別')),
                ('date', models.DateField(verbose_name='取引日付')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='金額')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='摘要')),
                ('is_posted', models.BooleanField(default=False, verbose_name='起票済')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.customer', verbose_name='得意先')),
            ],
            options={
                'verbose_name': '取引',
                'verbose_name_plural': '取引',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
